module.exports = [
  // "https://github.com/reactjs/reactjs.org",
  "https://github.com/kentcdodds/kentcdodds.com",
  // "https://github.com/hackclub/v2",
  // "https://github.com/peduarte/dona-rita-website",
  "https://github.com/phacks/theatres-parisiens",
  "https://github.com/calpa/gatsby-starter-calpa-blog",
  // "https://github.com/darrenbritton/darrenbritton.github.io",
  // "https://github.com/Dave-Lindberg/dl-gatsby",
  // "https://github.com/freeCodeCamp/guide",
  "https://github.com/kristofferh/kristoffer",
  "https://github.com/knpwrs/knpw.rs",
  "https://github.com/kbariotis/kostasbariotis.com",
  // "https://github.com/oleglegun/lasertime",
  "https://github.com/KyleAMathews/blog",
  "https://github.com/gabdorf/gabriel-adorf-portfolio",
  // "https://github.com/michelemazzucco/michelemazzucco.it",
  // "https://github.com/junkboy0315/yuuni-web",
  "https://github.com/kremalicious/portfolio",
  // "https://github.com/moetezch/moetez.me",
  "https://github.com/haxzie/sosc-website",
  // "https://github.com/mhjadav/mojaave",
  "https://github.com/thorium-sim/thoriumsim.com",
  "https://github.com/bchiang7/v4",
  // "https://github.com/MayerMediaCo/MayerMediaCo2.0",
  "https://github.com/jumpalottahigh/blog.georgi-yanev.com",
  "https://github.com/Manoz/k-legrand.com",
  // "https://github.com/daviddeejjames/dfjames-gatsby",
  // "https://github.com/codeformuenster/weihnachtsmarkt",
  // "https://github.com/qhacks/qhacks-website",
  // "https://github.com/devrchancay/personal-site",
  "https://github.com/lannonbr/vscode-rocks",
  "https://github.com/jacobdcastro/personal-site",
  "https://github.com/ooloth/gatsby-tutorials",
  "https://github.com/kylemcd/personal-site-react",
  // "https://github.com/fedonman/fedonman-website",
  "https://github.com/ParalelnaPolisKE/paralelnapoliskosice.sk",
  // "https://github.com/davemullenjnr/sheffielders",
  // "https://github.com/KeziahMoselle/blog.keziahmoselle.fr",
  // "https://github.com/aravindballa/website2017",
  "https://github.com/michalczaplinski/michalczaplinski.github.io",
  // "https://github.com/joshglazer/spotyou",
  // "https://github.com/hesamkaveh/sansi",
  // "https://github.com/JCofman/jc-website",
  // "https://github.com/sadnessOjisan/re-geo-lp",
  // "https://github.com/lcestou/luiscestou.com"
  // "https://github.com/abeaclark/weareclarks"
];
